typography_spectrum: 0.9604397201910615
color:
  brandStrength: 0.839873981429264
  lightness: 0.9221638697199523
  saturation: 0.589389372849837
  rhythmicContrast: 0.8830320967826992
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
opengraph:
  type: ''
layout_spectrum: 0.7835718649439514
author:
  email: betheproduct@icloud.com
  url: www.DennisSchoofs.com
  name: Dennis Schoofs
name: Werk Slimmer
navigation:
  - name: COACHING
    id: 855c75b4-ac8a-4a2b-9693-ff393f712d6a
    type: content
title: WERK SLIMMER
description: en niet harder
